site_name: Random Loot Roller

theme:
    name: "material"

plugins:
    - mkdocstrings

nav:
  - Random Loot Roller Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md